[package]
name = "mi7-reverse"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.36", features = ["full"] }
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
config = "0.14"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
